name: Rust

on:
  push:
    branches: [ "main", "next" ]
  pull_request:
    branches: [ "main", "next" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check code with Clippy
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        toolchain: stable
    - name: Check code formatting with rustfmt
      uses: actions-rust-lang/rustfmt@v1.0.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
